# Generated by Django 3.1.3 on 2020-11-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockList',
        ),
    ]
